services:
  - type: web
    name: pisos-elite-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pisos-elite-db
          property: connectionString